import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google"; 
import "./globals.css";

export const metadata: Metadata = {
  title: "FitChecker",
  description: "Generated by create next app",
};

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={josefinSans.className}>
        {children}
      </body>
    </html>
  );
}
